export const defaultThemes = [
    {
        name: 'test0',
        backgroundColor: '#A5BE00',
        backgroundColor2: '#679436',
        backgroundColor3: '#FFFCF2',
        borderColor: '#679436',
        color: '#FFF',
        color2: '#FFF',
        tableRx: 10,
        tableRy: 10,
        tableWidth: 220,
        rowHeight: 24,
        titleFontSize: '20px',
        titleFontWeight: 'bold',
        titleColor: '#FFF',
        rowFontSize: '20px',
        rowFontWeight: 'normal',
        rowColor: '#FFF',
        schemaFontSize: '50px',
        schemaFontWeight: '500',
        schemaColor: '#000'
    },
    {
        name: 'test1',
        backgroundColor: '#05668D',
        backgroundColor2: '#427AA1',
        backgroundColor3: '#FFFCF2',
        borderColor: '#427AA1',
        color: '#FFF',
        color2: '#FFF',
        tableRx: 10,
        tableRy: 10,
        tableWidth: 220,
        rowHeight: 24,
        titleFontSize: '20px',
        titleFontWeight: 'bold',
        titleColor: '#FFF',
        rowFontSize: '20px',
        rowFontWeight: 'normal',
        rowColor: '#FFF',
        schemaFontSize: '50px',
        schemaFontWeight: '500',
        schemaColor: '#000'
    },
    {
        name: 'test2',
        backgroundColor: '#d00000',
        backgroundColor2: '#D44D5C',
        backgroundColor3: '#FFFCF2',
        borderColor: '#D44D5C',
        color: '#FFF',
        color2: '#FFF',
        tableRx: 10,
        tableRy: 10,
        tableWidth: 220,
        rowHeight: 24,
        titleFontSize: '20px',
        titleFontWeight: 'bold',
        titleColor: '#FFF',
        rowFontSize: '20px',
        rowFontWeight: 'normal',
        rowColor: '#FFF',
        schemaFontSize: '50px',
        schemaFontWeight: '500',
        schemaColor: '#000'
    },
    {
        name: 'test3',
        backgroundColor: '#bfd200',
        backgroundColor2: '#55a630',
        backgroundColor3: '#000',
        borderColor: '#55a630',
        color: '#FFF',
        color2: '#FFF',
        tableRx: 10,
        tableRy: 10,
        tableWidth: 220,
        rowHeight: 24,
        titleFontSize: '20px',
        titleFontWeight: 'bold',
        titleColor: '#FFF',
        rowFontSize: '20px',
        rowFontWeight: 'normal',
        rowColor: '#FFF',
        schemaFontSize: '50px',
        schemaFontWeight: '500',
        schemaColor: '#FFF'
    }
];
